version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.45.2
    container_name: prometheus
    volumes:
      - /tmp/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - backend

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - backend

volumes:
  grafana-storage: {}

networks:
  backend:
    driver: bridge
